id: P27788980
initial_creation_type: ocr
source_metadata:
  volumes:
    03fc9ec9f4b34d57ae69af47c35c8457:
      base_file: v078.txt
      image_group_id: I1PD95923
      title: སྡོམ་པ་ཉི་ཤུ་པའི་འགྲེལ་པ།
      total_pages: 1254
      volume_number: 78
